# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    order_upload_directory: '%kernel.project_dir%/var/uploads/orders'
    monthly_plan_upload_directory: '%kernel.project_dir%/var/uploads/monthly-plans'
    working_documentation_upload_directory: '%kernel.project_dir%/var/uploads/working-documents'
    procurement_request_upload_directory: '%kernel.project_dir%/var/uploads/procurement-requests'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\ProductionOrderFileStorage:
        arguments:
            $uploadDirectory: '%order_upload_directory%'

    App\Service\MonthlyProductionPlanFileStorage:
        arguments:
            $uploadDirectory: '%monthly_plan_upload_directory%'

    App\Service\WorkingDocumentationFileStorage:
        arguments:
            $uploadDirectory: '%working_documentation_upload_directory%'

    App\Service\MaterialProcurementRequestFileStorage:
        arguments:
            $uploadDirectory: '%procurement_request_upload_directory%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
