<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260713120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds workflow status and event history for material procurement requests.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE material_procurement_requests ADD status VARCHAR(30) DEFAULT 'draft' NOT NULL");
        $this->addSql('ALTER TABLE material_procurement_requests ADD submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE material_procurement_requests ADD submitted_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE material_procurement_requests ADD accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE material_procurement_requests ADD accepted_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE material_procurement_requests ADD purchased_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE material_procurement_requests ADD purchased_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE material_procurement_requests ADD received_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE material_procurement_requests ADD received_by_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_STATUS ON material_procurement_requests (status)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_SUBMITTED_BY ON material_procurement_requests (submitted_by_id)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_ACCEPTED_BY ON material_procurement_requests (accepted_by_id)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_PURCHASED_BY ON material_procurement_requests (purchased_by_id)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_RECEIVED_BY ON material_procurement_requests (received_by_id)');
        $this->addSql('ALTER TABLE material_procurement_requests ADD CONSTRAINT FK_PROCUREMENT_REQUEST_SUBMITTED_BY FOREIGN KEY (submitted_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE material_procurement_requests ADD CONSTRAINT FK_PROCUREMENT_REQUEST_ACCEPTED_BY FOREIGN KEY (accepted_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE material_procurement_requests ADD CONSTRAINT FK_PROCUREMENT_REQUEST_PURCHASED_BY FOREIGN KEY (purchased_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE material_procurement_requests ADD CONSTRAINT FK_PROCUREMENT_REQUEST_RECEIVED_BY FOREIGN KEY (received_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE material_procurement_request_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, request_id INT NOT NULL, created_by_id INT DEFAULT NULL, from_status VARCHAR(30) DEFAULT NULL, to_status VARCHAR(30) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_EVENTS_REQUEST ON material_procurement_request_events (request_id)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_EVENTS_CREATED_BY ON material_procurement_request_events (created_by_id)');
        $this->addSql('ALTER TABLE material_procurement_request_events ADD CONSTRAINT FK_PROCUREMENT_REQUEST_EVENTS_REQUEST FOREIGN KEY (request_id) REFERENCES material_procurement_requests (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE material_procurement_request_events ADD CONSTRAINT FK_PROCUREMENT_REQUEST_EVENTS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE material_procurement_request_events');
        $this->addSql('ALTER TABLE material_procurement_requests DROP CONSTRAINT FK_PROCUREMENT_REQUEST_SUBMITTED_BY');
        $this->addSql('ALTER TABLE material_procurement_requests DROP CONSTRAINT FK_PROCUREMENT_REQUEST_ACCEPTED_BY');
        $this->addSql('ALTER TABLE material_procurement_requests DROP CONSTRAINT FK_PROCUREMENT_REQUEST_PURCHASED_BY');
        $this->addSql('ALTER TABLE material_procurement_requests DROP CONSTRAINT FK_PROCUREMENT_REQUEST_RECEIVED_BY');
        $this->addSql('DROP INDEX IDX_PROCUREMENT_REQUEST_STATUS');
        $this->addSql('DROP INDEX IDX_PROCUREMENT_REQUEST_SUBMITTED_BY');
        $this->addSql('DROP INDEX IDX_PROCUREMENT_REQUEST_ACCEPTED_BY');
        $this->addSql('DROP INDEX IDX_PROCUREMENT_REQUEST_PURCHASED_BY');
        $this->addSql('DROP INDEX IDX_PROCUREMENT_REQUEST_RECEIVED_BY');
        $this->addSql('ALTER TABLE material_procurement_requests DROP status');
        $this->addSql('ALTER TABLE material_procurement_requests DROP submitted_at');
        $this->addSql('ALTER TABLE material_procurement_requests DROP submitted_by_id');
        $this->addSql('ALTER TABLE material_procurement_requests DROP accepted_at');
        $this->addSql('ALTER TABLE material_procurement_requests DROP accepted_by_id');
        $this->addSql('ALTER TABLE material_procurement_requests DROP purchased_at');
        $this->addSql('ALTER TABLE material_procurement_requests DROP purchased_by_id');
        $this->addSql('ALTER TABLE material_procurement_requests DROP received_at');
        $this->addSql('ALTER TABLE material_procurement_requests DROP received_by_id');
    }
}