<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608194157 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_email VARCHAR(180) DEFAULT NULL, user_name VARCHAR(255) DEFAULT NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(120) NOT NULL, entity_id INT DEFAULT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, context JSON DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D62F2858A76ED395 ON audit_logs (user_id)');
        $this->addSql('CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_action ON audit_logs (action)');
        $this->addSql('CREATE INDEX idx_audit_created_at ON audit_logs (created_at)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, full_name VARCHAR(255) NOT NULL, position VARCHAR(255) DEFAULT NULL, workshop VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE otk_inspections ADD executor_user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE otk_inspections ADD controller_user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE otk_inspections ADD CONSTRAINT FK_78D1E13B679ED481 FOREIGN KEY (executor_user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE otk_inspections ADD CONSTRAINT FK_78D1E13B4059EE54 FOREIGN KEY (controller_user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_78D1E13B679ED481 ON otk_inspections (executor_user_id)');
        $this->addSql('CREATE INDEX IDX_78D1E13B4059EE54 ON otk_inspections (controller_user_id)');
        $this->addSql('ALTER TABLE shift_tasks ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE shift_tasks ADD issued_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE shift_tasks ADD closed_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE shift_tasks ADD CONSTRAINT FK_5BB683C9B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_tasks ADD CONSTRAINT FK_5BB683C9784BB717 FOREIGN KEY (issued_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_tasks ADD CONSTRAINT FK_5BB683C9E1FA7797 FOREIGN KEY (closed_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_5BB683C9B03A8386 ON shift_tasks (created_by_id)');
        $this->addSql('CREATE INDEX IDX_5BB683C9784BB717 ON shift_tasks (issued_by_id)');
        $this->addSql('CREATE INDEX IDX_5BB683C9E1FA7797 ON shift_tasks (closed_by_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE users');
        $this->addSql('ALTER TABLE otk_inspections DROP CONSTRAINT FK_78D1E13B679ED481');
        $this->addSql('ALTER TABLE otk_inspections DROP CONSTRAINT FK_78D1E13B4059EE54');
        $this->addSql('DROP INDEX IDX_78D1E13B679ED481');
        $this->addSql('DROP INDEX IDX_78D1E13B4059EE54');
        $this->addSql('ALTER TABLE otk_inspections DROP executor_user_id');
        $this->addSql('ALTER TABLE otk_inspections DROP controller_user_id');
        $this->addSql('ALTER TABLE shift_tasks DROP CONSTRAINT FK_5BB683C9B03A8386');
        $this->addSql('ALTER TABLE shift_tasks DROP CONSTRAINT FK_5BB683C9784BB717');
        $this->addSql('ALTER TABLE shift_tasks DROP CONSTRAINT FK_5BB683C9E1FA7797');
        $this->addSql('DROP INDEX IDX_5BB683C9B03A8386');
        $this->addSql('DROP INDEX IDX_5BB683C9784BB717');
        $this->addSql('DROP INDEX IDX_5BB683C9E1FA7797');
        $this->addSql('ALTER TABLE shift_tasks DROP created_by_id');
        $this->addSql('ALTER TABLE shift_tasks DROP issued_by_id');
        $this->addSql('ALTER TABLE shift_tasks DROP closed_by_id');
    }
}
