<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260502112430 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE otk_inspections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, name VARCHAR(255) NOT NULL, project VARCHAR(255) NOT NULL, presented_quantity INT NOT NULL, accepted_quantity INT NOT NULL, rejected_quantity INT NOT NULL, nonconformity_description TEXT DEFAULT NULL, nonconformity_act_number VARCHAR(100) DEFAULT NULL, executor_name VARCHAR(255) DEFAULT NULL, controller_name VARCHAR(255) DEFAULT NULL, executor_signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, controller_signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON COLUMN shift_task_items.mark IS \'\'');
        $this->addSql('COMMENT ON COLUMN shift_task_items.note IS \'\'');
        $this->addSql('COMMENT ON COLUMN shift_tasks.workshop IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE otk_inspections');
        $this->addSql('COMMENT ON COLUMN shift_task_items.mark IS \'Марка/Модель\'');
        $this->addSql('COMMENT ON COLUMN shift_task_items.note IS \'Примечание\'');
        $this->addSql('COMMENT ON COLUMN shift_tasks.workshop IS \'Название цеха\'');
    }
}
