<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260622120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds production orders and their uploaded files.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE production_orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(100) DEFAULT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(30) NOT NULL, issued_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT DEFAULT NULL, issued_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_production_orders_number ON production_orders (number)');
        $this->addSql('CREATE INDEX IDX_PRODUCTION_ORDERS_CREATED_BY ON production_orders (created_by_id)');
        $this->addSql('CREATE INDEX IDX_PRODUCTION_ORDERS_ISSUED_BY ON production_orders (issued_by_id)');
        $this->addSql('ALTER TABLE production_orders ADD CONSTRAINT FK_PRODUCTION_ORDERS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_orders ADD CONSTRAINT FK_PRODUCTION_ORDERS_ISSUED_BY FOREIGN KEY (issued_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE production_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, payload JSON DEFAULT NULL, production_order_id INT NOT NULL, created_by_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_PRODUCTION_DOCUMENT_ORDER ON production_document (production_order_id)');
        $this->addSql('CREATE INDEX IDX_PRODUCTION_DOCUMENT_CREATED_BY ON production_document (created_by_id)');
        $this->addSql('CREATE INDEX IDX_PRODUCTION_DOCUMENT_APPROVED_BY ON production_document (approved_by_id)');
        $this->addSql('ALTER TABLE production_document ADD CONSTRAINT FK_PRODUCTION_DOCUMENT_ORDER FOREIGN KEY (production_order_id) REFERENCES production_orders (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_document ADD CONSTRAINT FK_PRODUCTION_DOCUMENT_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_document ADD CONSTRAINT FK_PRODUCTION_DOCUMENT_APPROVED_BY FOREIGN KEY (approved_by_id) REFERENCES users (id) NOT DEFERRABLE');

        $this->addSql('CREATE TABLE production_order_files (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, mime_type VARCHAR(150) NOT NULL, size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, production_order_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PRODUCTION_ORDER_FILES_STORED_NAME ON production_order_files (stored_name)');
        $this->addSql('CREATE INDEX IDX_PRODUCTION_ORDER_FILES_ORDER ON production_order_files (production_order_id)');
        $this->addSql('CREATE INDEX IDX_PRODUCTION_ORDER_FILES_UPLOADED_BY ON production_order_files (uploaded_by_id)');
        $this->addSql('ALTER TABLE production_order_files ADD CONSTRAINT FK_PRODUCTION_ORDER_FILES_ORDER FOREIGN KEY (production_order_id) REFERENCES production_orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_order_files ADD CONSTRAINT FK_PRODUCTION_ORDER_FILES_UPLOADED_BY FOREIGN KEY (uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE production_order_files');
        $this->addSql('DROP TABLE production_document');
        $this->addSql('DROP TABLE production_orders');
    }
}
