<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260714120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds document workflows, approval history and task assignments.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE document_workflows (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, document_type VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(30) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_WORKFLOWS_STATUS ON document_workflows (status)');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_WORKFLOWS_CREATED_BY ON document_workflows (created_by_id)');
        $this->addSql('ALTER TABLE document_workflows ADD CONSTRAINT FK_DOCUMENT_WORKFLOWS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE document_workflow_files (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workflow_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, mime_type VARCHAR(150) NOT NULL, size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DOCUMENT_WORKFLOW_FILES_STORED_NAME ON document_workflow_files (stored_name)');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_WORKFLOW_FILES_WORKFLOW ON document_workflow_files (workflow_id)');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_WORKFLOW_FILES_UPLOADED_BY ON document_workflow_files (uploaded_by_id)');
        $this->addSql('ALTER TABLE document_workflow_files ADD CONSTRAINT FK_DOCUMENT_WORKFLOW_FILES_WORKFLOW FOREIGN KEY (workflow_id) REFERENCES document_workflows (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_workflow_files ADD CONSTRAINT FK_DOCUMENT_WORKFLOW_FILES_UPLOADED_BY FOREIGN KEY (uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE document_approval_steps (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workflow_id INT NOT NULL, approver_id INT DEFAULT NULL, sort_order INT NOT NULL, status VARCHAR(30) NOT NULL, comment TEXT DEFAULT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_APPROVAL_STEPS_WORKFLOW ON document_approval_steps (workflow_id)');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_APPROVAL_STEPS_APPROVER ON document_approval_steps (approver_id)');
        $this->addSql('ALTER TABLE document_approval_steps ADD CONSTRAINT FK_DOCUMENT_APPROVAL_STEPS_WORKFLOW FOREIGN KEY (workflow_id) REFERENCES document_workflows (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_approval_steps ADD CONSTRAINT FK_DOCUMENT_APPROVAL_STEPS_APPROVER FOREIGN KEY (approver_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE document_workflow_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workflow_id INT NOT NULL, created_by_id INT DEFAULT NULL, event_type VARCHAR(50) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_WORKFLOW_EVENTS_WORKFLOW ON document_workflow_events (workflow_id)');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_WORKFLOW_EVENTS_CREATED_BY ON document_workflow_events (created_by_id)');
        $this->addSql('ALTER TABLE document_workflow_events ADD CONSTRAINT FK_DOCUMENT_WORKFLOW_EVENTS_WORKFLOW FOREIGN KEY (workflow_id) REFERENCES document_workflows (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_workflow_events ADD CONSTRAINT FK_DOCUMENT_WORKFLOW_EVENTS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE task_assignments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, responsible_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, document_workflow_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(30) NOT NULL, due_date DATE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_TASK_ASSIGNMENTS_RESPONSIBLE ON task_assignments (responsible_id)');
        $this->addSql('CREATE INDEX IDX_TASK_ASSIGNMENTS_CREATED_BY ON task_assignments (created_by_id)');
        $this->addSql('CREATE INDEX IDX_TASK_ASSIGNMENTS_DOCUMENT_WORKFLOW ON task_assignments (document_workflow_id)');
        $this->addSql('CREATE INDEX IDX_TASK_ASSIGNMENTS_STATUS_DUE ON task_assignments (status, due_date)');
        $this->addSql('ALTER TABLE task_assignments ADD CONSTRAINT FK_TASK_ASSIGNMENTS_RESPONSIBLE FOREIGN KEY (responsible_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_assignments ADD CONSTRAINT FK_TASK_ASSIGNMENTS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_assignments ADD CONSTRAINT FK_TASK_ASSIGNMENTS_DOCUMENT_WORKFLOW FOREIGN KEY (document_workflow_id) REFERENCES document_workflows (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE task_assignment_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, assignment_id INT NOT NULL, created_by_id INT DEFAULT NULL, event_type VARCHAR(50) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_TASK_ASSIGNMENT_EVENTS_ASSIGNMENT ON task_assignment_events (assignment_id)');
        $this->addSql('CREATE INDEX IDX_TASK_ASSIGNMENT_EVENTS_CREATED_BY ON task_assignment_events (created_by_id)');
        $this->addSql('ALTER TABLE task_assignment_events ADD CONSTRAINT FK_TASK_ASSIGNMENT_EVENTS_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES task_assignments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_assignment_events ADD CONSTRAINT FK_TASK_ASSIGNMENT_EVENTS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE task_assignment_events');
        $this->addSql('DROP TABLE task_assignments');
        $this->addSql('DROP TABLE document_workflow_events');
        $this->addSql('DROP TABLE document_approval_steps');
        $this->addSql('DROP TABLE document_workflow_files');
        $this->addSql('DROP TABLE document_workflows');
    }
}