<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260622190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds monthly production planning and its uploaded files.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE monthly_production_plans (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, month DATE NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_MONTHLY_PLANS_CREATED_BY ON monthly_production_plans (created_by_id)');
        $this->addSql('CREATE INDEX IDX_MONTHLY_PLANS_MONTH ON monthly_production_plans (month)');
        $this->addSql('ALTER TABLE monthly_production_plans ADD CONSTRAINT FK_MONTHLY_PLANS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE monthly_production_plan_files (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, mime_type VARCHAR(150) NOT NULL, size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, monthly_plan_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MONTHLY_PLAN_FILES_STORED_NAME ON monthly_production_plan_files (stored_name)');
        $this->addSql('CREATE INDEX IDX_MONTHLY_PLAN_FILES_PLAN ON monthly_production_plan_files (monthly_plan_id)');
        $this->addSql('CREATE INDEX IDX_MONTHLY_PLAN_FILES_UPLOADED_BY ON monthly_production_plan_files (uploaded_by_id)');
        $this->addSql('ALTER TABLE monthly_production_plan_files ADD CONSTRAINT FK_MONTHLY_PLAN_FILES_PLAN FOREIGN KEY (monthly_plan_id) REFERENCES monthly_production_plans (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE monthly_production_plan_files ADD CONSTRAINT FK_MONTHLY_PLAN_FILES_UPLOADED_BY FOREIGN KEY (uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE monthly_production_plan_files');
        $this->addSql('DROP TABLE monthly_production_plans');
    }
}
