<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260623100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds working documentation packages linked to monthly plans.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE working_documentation_packages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, monthly_plan_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_WORKING_DOCS_MONTHLY_PLAN ON working_documentation_packages (monthly_plan_id)');
        $this->addSql('CREATE INDEX IDX_WORKING_DOCS_CREATED_BY ON working_documentation_packages (created_by_id)');
        $this->addSql('ALTER TABLE working_documentation_packages ADD CONSTRAINT FK_WORKING_DOCS_MONTHLY_PLAN FOREIGN KEY (monthly_plan_id) REFERENCES monthly_production_plans (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE working_documentation_packages ADD CONSTRAINT FK_WORKING_DOCS_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE working_documentation_files (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, mime_type VARCHAR(150) NOT NULL, size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, package_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WORKING_DOC_FILES_STORED_NAME ON working_documentation_files (stored_name)');
        $this->addSql('CREATE INDEX IDX_WORKING_DOC_FILES_PACKAGE ON working_documentation_files (package_id)');
        $this->addSql('CREATE INDEX IDX_WORKING_DOC_FILES_UPLOADED_BY ON working_documentation_files (uploaded_by_id)');
        $this->addSql('ALTER TABLE working_documentation_files ADD CONSTRAINT FK_WORKING_DOC_FILES_PACKAGE FOREIGN KEY (package_id) REFERENCES working_documentation_packages (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE working_documentation_files ADD CONSTRAINT FK_WORKING_DOC_FILES_UPLOADED_BY FOREIGN KEY (uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE working_documentation_files');
        $this->addSql('DROP TABLE working_documentation_packages');
    }
}
