<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260501121859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shift_task_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mark TEXT NOT NULL, first_shift_plan INT DEFAULT NULL, first_shift_fact INT DEFAULT NULL, second_shift_plan INT DEFAULT NULL, second_shift_fact INT DEFAULT NULL, note TEXT DEFAULT NULL, sort_order INT NOT NULL, section_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1205B942D823E37A ON shift_task_items (section_id)');
        $this->addSql('CREATE TABLE shift_task_sections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sort_order INT NOT NULL, shift_task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_101490EEE0E73DFF ON shift_task_sections (shift_task_id)');
        $this->addSql('CREATE TABLE shift_tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, title VARCHAR(255) NOT NULL, workshop VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE shift_task_items ADD CONSTRAINT FK_1205B942D823E37A FOREIGN KEY (section_id) REFERENCES shift_task_sections (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_task_sections ADD CONSTRAINT FK_101490EEE0E73DFF FOREIGN KEY (shift_task_id) REFERENCES shift_tasks (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shift_task_items DROP CONSTRAINT FK_1205B942D823E37A');
        $this->addSql('ALTER TABLE shift_task_sections DROP CONSTRAINT FK_101490EEE0E73DFF');
        $this->addSql('DROP TABLE shift_task_items');
        $this->addSql('DROP TABLE shift_task_sections');
        $this->addSql('DROP TABLE shift_tasks');
    }
}
