<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260623140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds material procurement requests linked to multiple orders.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE material_procurement_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, month DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_MONTH ON material_procurement_requests (month)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_CREATED_BY ON material_procurement_requests (created_by_id)');
        $this->addSql('ALTER TABLE material_procurement_requests ADD CONSTRAINT FK_PROCUREMENT_REQUEST_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE material_procurement_request_orders (request_id INT NOT NULL, production_order_id INT NOT NULL, PRIMARY KEY (request_id, production_order_id))');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_ORDER_REQUEST ON material_procurement_request_orders (request_id)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_ORDER_ORDER ON material_procurement_request_orders (production_order_id)');
        $this->addSql('ALTER TABLE material_procurement_request_orders ADD CONSTRAINT FK_PROCUREMENT_ORDER_REQUEST FOREIGN KEY (request_id) REFERENCES material_procurement_requests (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE material_procurement_request_orders ADD CONSTRAINT FK_PROCUREMENT_ORDER_ORDER FOREIGN KEY (production_order_id) REFERENCES production_orders (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql('CREATE TABLE material_procurement_request_files (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, mime_type VARCHAR(150) NOT NULL, size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROCUREMENT_REQUEST_FILES_STORED_NAME ON material_procurement_request_files (stored_name)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_FILES_REQUEST ON material_procurement_request_files (request_id)');
        $this->addSql('CREATE INDEX IDX_PROCUREMENT_REQUEST_FILES_UPLOADED_BY ON material_procurement_request_files (uploaded_by_id)');
        $this->addSql('ALTER TABLE material_procurement_request_files ADD CONSTRAINT FK_PROCUREMENT_REQUEST_FILES_REQUEST FOREIGN KEY (request_id) REFERENCES material_procurement_requests (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE material_procurement_request_files ADD CONSTRAINT FK_PROCUREMENT_REQUEST_FILES_UPLOADED_BY FOREIGN KEY (uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE material_procurement_request_files');
        $this->addSql('DROP TABLE material_procurement_request_orders');
        $this->addSql('DROP TABLE material_procurement_requests');
    }
}
