export const ORDER_PARTICIPANT_ROLES = [
  'ROLE_PTO_HEAD',
  'ROLE_PTO_DEPUTY_HEAD',
  'ROLE_PTO_ENGINEER',
  'ROLE_CHIEF_WELDER',
  'ROLE_CHIEF_TECHNOLOGIST',
  'ROLE_PO_HEAD',
  'ROLE_GENERAL_DIRECTOR',
  'ROLE_ECONOMIST',
  'ROLE_SALES_HEAD',
  'ROLE_SALES_MANAGER',
  'ROLE_RESPONSIBLE_EXECUTOR',
  'ROLE_LEAD_DESIGN_ENGINEER',
  'ROLE_ADMIN'
]

export function canAccessOrders(roles = []) {
  return ORDER_PARTICIPANT_ROLES.some(role => roles.includes(role))
}
