security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        api_token:
            pattern: ^/api/token
            stateless: true

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            access_token:
                token_handler: App\Security\AccessTokenHandler

    access_control:
        - { path: ^/api/token, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/analytics, roles: [ROLE_MANAGER, ROLE_ADMIN] }
        - { path: ^/api/otk-inspections, roles: [ROLE_CONTROLLER_OTK] }
        - { path: ^/api/shift-tasks, roles: [ROLE_CRO, ROLE_SSC, ROLE_CPO] }
